name: Deploy Vue to GitHub Pages

on:
  push:
    branches:
      - main  # 你可以根据需要更改为你的默认分支（如 master）

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # 可以选择你项目使用的 Node.js 版本
        cache: 'npm'

    - name: Install yarm
      run: |
        npm install yarn

    - name: Install dependencies yarn
      run: |
        yarn install

    - name: Build the project
      run: |
        npm run build  # 构建你的 Vue 项目

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # 部署到 gh-pages 分支
        folder: dist  # Vue 项目构建后输出的文件夹（通常是 dist）
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
